version: "3.7"
services:
    frontend:
        container_name: container_name
        build:
            context: ./client
            dockerfile: Dockerfile
        image: project/container_name
        ports:
            - "3000:3000"
        volumes:
            - ./client:/app
            - /app/node_modules
        environment:
            - NODE_ENV=development