version: "3"
services:
    frontend:
        container_name: container_name
        build:
            context: ./client
            dockerfile: Dockerfile
        image: app/container_name
        ports:
            - "3000:3000"
        volumes:
            - ./client:/usr/src/app